version: "3.3"

services:
  lighttpd:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.lighttpd
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./bones_data/repos:/repos/user
      - ./shared:/shared:ro
      - ./lighttpd_config:/etc/lighttpd:ro

  bones:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile.ruby
    restart: always
    volumes:
      - ./bones_data:/bones_data
      - ./shared:/shared:ro
    environment:
      DATABASE_URL: "sqlite:///bones_data/bones.db"
      REPO_ROOT: "/bones_data/repos"
      FOSSIL_BINARY: "/shared/fossil"
      SESSION_SECRET:
