bones:
  repository_root: <%= ENV["REPO_ROOT"] %>
  fossil_binary: <%= ENV["FOSSIL_BINARY"] %>

database:
  url: <%= ENV.delete("DATABASE_URL") %>

domain: http://localhost:3000
email_from: no-reply@dev+bones.isin.space

mail:
  delivery_method: logger
  #delivery_method: test
  #delivery_method: smtp
  #delivery_config:
     #address: "localhost"
     #port: 1025

feature_flags:
  sign_up: false
