bones:
  repository_root: ./tmp
  fossil_binary: <%= ENV["FOSSIL_BINARY"] %>

domain: https://bones.isin.space
email_from: no-reply@bones.isin.space

mail:
  delivery_method: test

feature_flags:
  sign_up: false
